#!/bin/bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Launch a browser with Mongo Express
## Usage: mongo-express
## Example: "ddev mongo-express"

# Determine whether to use HTTP or HTTPS based on environment
PROTOCOL="HTTP"
if [ "${DDEV_PRIMARY_URL%://*}" != "http" ] && [ -z "${GITPOD_WORKSPACE_ID:-}" ] && [ "${CODESPACES:-}" != "true" ]; then
    PROTOCOL="HTTPS"
fi

# Fetch the appropriate port within the mongo-express container
DDEV_MONGO_EXPRESS_PORT=$(ddev exec -s mongo-express sh -c "printenv | grep -w ${PROTOCOL}_EXPOSE | cut -d '=' -f 2 | cut -d ':' -f 1")

if [ -z "$DDEV_MONGO_EXPRESS_PORT" ]; then
    echo "Error: Could not retrieve Mongo Express port."
    exit 1
fi

ddev launch :"$DDEV_MONGO_EXPRESS_PORT"

