#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run
# ddev get ddev/ddev-mongo
#
# This file comes from https://github.com/ddev/ddev-mongo
#
services:
  mongo:
    container_name: ddev-${DDEV_SITENAME}-mongo
    image: mongo:5-focal
    volumes:
    - type: "volume"
      source: mongo
      target: "/data/db"
      volume:
        nocopy: true
    - ".:/mnt/ddev_config"
    restart: "no"
    expose:
    - "27017"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
    - MONGO_INITDB_ROOT_USERNAME=db
    - MONGO_INITDB_ROOT_PASSWORD=db
    - MONGO_INITDB_DATABASE=db
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand(\"ping\").ok' localhost:27017/test --quiet"]
      timeout: 60s

  mongo-express:
    container_name: ddev-${DDEV_SITENAME}-mongo-express
    image: mongo-express:0.54
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
      com.ddev.platform: ddev
    expose:
    - "8081"
    environment:
      VIRTUAL_HOST: $DDEV_HOSTNAME
      ME_CONFIG_MONGODB_ADMINUSERNAME: db
      ME_CONFIG_MONGODB_ADMINPASSWORD: db
      HTTP_EXPOSE: "9091:8081"
    depends_on:
      - mongo

volumes:
  mongo:
